- name: Jenkins | Start Jenkins Container
  docker_container:
    name: jenkins
    image: jenkins/jenkins
    pull: true
    state: started
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - /mnt/app/:/var/jenkins_home


- name: Jenkins | Add  Java Repo
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Jenkins | Accept Java License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Jenkins |  Install Java8
  become: yes
  yum: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default